#! /usr/bin/env python
# -*- coding: utf-8 -*-

##############################################################################
##  -- PhyNetPy --                                                              
##  Library for the Development and use of Phylogenetic Network Methods
##
##  Copyright 2025 Mark Kessler, Luay Nakhleh.
##  All rights reserved.
##
##  See "LICENSE.txt" for terms and conditions of usage.
##
##  If you use this work or any portion thereof in published work,
##  please cite it as:
##
##     Mark Kessler, Luay Nakhleh. 2025.
##
##############################################################################

""" 
Author : Mark Kessler
Last Stable Edit : 6/09/26
First Included in Version : 0.6.0
Approved for Release Date : No
"""

from IO import *
from Network import *
import subprocess, tempfile, os

def _preprocess(newick_str : str) -> str:
    """
    Convert a newick string to a newick string that is free of inheritance probs
    and any other artifacts Dendroscope can't handle

    Args:
        newick_str (str): A newick string generated by a net.newick() call. 

    Returns:
        str: A newick string that Dendroscope can process.
    """
    #TODO: do this 
    return str

def view_in_dendroscope(net : Network , dendroscope_path="/Applications/Dendroscope.app") -> None:
    """
    Open Dendroscope and view the Network!

    Args:
        net (Network): Any network.
        dendroscope_path (str, optional): Path to your installation of Dendroscope. Defaults to "/Applications/Dendroscope.app".
    """
    enewick = net.newick()            
    tmp = tempfile.NamedTemporaryFile(
        suffix=".tre", mode="w", delete=False
    )
    tmp.write(enewick + "\n")
    tmp.flush()
    subprocess.Popen([
        "java", "-jar", f"{dendroscope_path}/Contents/Java/dendroscope.jar",
        tmp.name
    ])